### ISSUE TITLE
Sync doesn't work

### ISSUE THREAD

**Issue by cordawyn** [kotyo/clj-rocksdb#1]
Hi!

It seems that this
https://github.com/kotyo/clj-rocksdb/blob/master/src/clj_rocksdb.clj#L335
should call `.setSync` (setter method) instead of `.sync` (getter method).
(You can check with https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/WriteOptions.java#L64)

Using `clj-rocksdb/sync db` crashes for me because of this.

**Comment by t44k** [comment]
:+1: Thank you for the comment. It is fixed now.
